# Generated by Django 6.0.7 on 2026-08-21 23:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatBot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_text', models.TextField()),
                ('chat', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='DailyBread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scripture_name', models.TextField(help_text='Bible reference')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('author', models.CharField(help_text=' the person who wrote the passage')),
            ],
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=100)),
                ('event_date', models.DateField(blank=True, help_text='date of the event', null=True)),
                ('event_location', models.CharField(max_length=100)),
                ('event_description', models.TextField()),
                ('event_image', models.ImageField(upload_to='events/')),
            ],
        ),
        migrations.CreateModel(
            name='EventSales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product', models.CharField(help_text=' products that we have for sale')),
                ('description', models.TextField(help_text='a description of the product')),
                ('price', models.DecimalField(decimal_places=2, max_digits=3)),
                ('product_image', models.ImageField(blank=True, upload_to='products/')),
            ],
        ),
        migrations.CreateModel(
            name='LocalScripture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=100, unique=True)),
                ('reference', models.CharField(max_length=100)),
                ('reflection', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pastor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, help_text=' send this person a positive affirmations', max_length=254)),
                ('audio_segment', models.FileField(blank=True, upload_to='prayers_for_those_in_need/')),
                ('prayer', models.TextField(blank=True, help_text='add a prayer')),
            ],
        ),
        migrations.CreateModel(
            name='VideoSegments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_segment', models.FileField(upload_to='video/')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_segments', to='Events.events')),
            ],
        ),
    ]
